### ISSUE TITLE
Add a README file

### ISSUE THREAD

**Issue by ColinEberhardt** [bdimitrov-SL/PropertyCross-Site-Redesign#3]
I think the only thing left to do before merging this into https://github.com/ColinEberhardt/PropertyCross-Site is to add some instructions.

Can you please add a README that covers;
- Developer instructions, how do you get started? I guess it's little more than `npm i` and `gulp` ...
- Release instructions, I see you've got a gulp task for production release. 

Actually, regarding the second point, can you explore tasks that automate pushing to gh-pages? Here's an example:

https://www.npmjs.com/package/gulp-gh-pages

I've seen something similar used in the past, but don't have a preferred option.

**Comment by bdimitrov-SL** [comment]
Hi Colin,

I've added the README to the repo. Also I've added a 'deploy' task that pushes to gh-pages - instructions in the README :)

Cheers,
Bogdan
